### ISSUE TITLE
Estruturar código em arquivos diferentes

### ISSUE THREAD

**Issue by gusholz** [WellingtonDeOliveira/TaskIos1#2]
https://github.com/WellingtonDeOliveira/TaskIos1/blob/9d460fc41b2cb819d1e27ce6f8f8c35dd29ba87a/IosTask/main.swift#L1

Ao estruturar o código em diferentes arquivos e pastas, ele fica mais fácil de ser lido e mantido

**Comment by WellingtonDeOliveira** [comment]
Bem observado e desejo fazer isso, como foi a primeira vez criando um projeto com Swift não me preocupei tanto, mas irei fazer isso nas próxima atualizações/projetos.

**Comment by WellingtonDeOliveira** [comment]
resolvido
