### ISSUE TITLE
Função com mais de uma responsabilidade

### ISSUE THREAD

**Issue by gusholz** [WellingtonDeOliveira/TaskIos1#5]
https://github.com/WellingtonDeOliveira/TaskIos1/blob/9d460fc41b2cb819d1e27ce6f8f8c35dd29ba87a/IosTask/main.swift#L191-L231

Percebemos que a função editar, alem de editar, salva o arquivo. Recomendaríamos a titulo de melhoria jogar a responsabilidade de salvar para uma nova função

**Comment by WellingtonDeOliveira** [comment]
Bem observado mano, nem tinha me tocado que poderia ter feito assim.
