### ISSUE TITLE
Código morto não precisa ser upado

### ISSUE THREAD

**Issue by gusholz** [WellingtonDeOliveira/TaskIos1#6]
https://github.com/WellingtonDeOliveira/TaskIos1/blob/9d460fc41b2cb819d1e27ce6f8f8c35dd29ba87a/IosTask/main.swift#L257-L284

**Comment by WellingtonDeOliveira** [comment]
Era uma das opções do menu, eu não tirei totalmente, pois era algo que iria tentar resolver depois, mas boa observação.
