### ISSUE TITLE
Ao executar o código deu erro no trecho que selecionei, anexei a saída do terminal

### ISSUE THREAD

**Issue by Maurrici** [WellingtonDeOliveira/TaskIos1#8]
https://github.com/WellingtonDeOliveira/TaskIos1/blob/9d460fc41b2cb819d1e27ce6f8f8c35dd29ba87a/IosTask/main.swift#LL45C1-L51C2

<img width="1159" alt="Captura de Tela 2023-05-15 às 20 36 19" src="https://github.com/WellingtonDeOliveira/TaskIos1/assets/53577592/d6a2d661-23ad-413c-884c-75838bc3f2c2">

**Comment by WellingtonDeOliveira** [comment]
Boa mano, eu tinha visto aqui esse problema, e já reconheci o erro.
